# -----
image: atlassian/default-image:2

pipelines:
  # For the lab, we only care about the master branch
  branches:
    master:
      - step:
          # Put these variables in Repository Variables under Settings
          # set AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY as environment variables
          # These variables should be hidden on bitbucket - just FYI
          # set ZIPFILE to the archive you intend to upload
          # FILESTOZIP is the list of files you will include in archive
          # S3BUCKET is our destination upload bucket
          name: Zip and upload relevant files for AWS codepipeline to pick up
          deployment: production   # set to test, staging or production
          # trigger: manual  # uncomment to have a manual step
          image: atlassian/pipelines-awscli
          script:
            - apk --update add zip
            - zip $ZIPFILE $FILESTOZIP
            - aws s3 cp $ZIPFILE s3://$S3BUCKET/
